"use client"
import Footer from '@/components/Footer/Footer'
import HeroSection from '@/components/heroSection/HeroSection'
import Navbar from '@/components/Navbar/Navbar'
import Statistic from '@/components/Stats/Stats'
import Step from '@/components/Step/Step'
import Teams from '@/components/Teams/OurTeam'
import './globals.css'
import React from 'react'
import MoveToTop from '@/components/moveToTop/MoveToTop'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// some articles must be shown on the homepage
// before a user logs
// so users see what they can do on a website
export default function Layout({ children }) {

  const stepsComponentRef = React.useRef(null);
  return (
    <html lang="en">
      <body className="relative">
        <Navbar />
        <HeroSection stepsComponentRef={stepsComponentRef}/>
        <div ref={stepsComponentRef}>
          <Step /> 
        </div>
        <Statistic />
        <Teams />
        <Footer />
        <MoveToTop />
        {children}
      </body>
    </html>
  )
}
