import Footer from '@/components/Footer/Footer'
import HeroSection from '@/components/heroSection/HeroSection'
import Navbar from '@/components/Navbar/Navbar'
import Statistic from '@/components/Stats/Stats'
import Step from '@/components/Step/Step'
import Teams from '@/components/Teams/OurTeam'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

// some articles must be shown on the homepage
// before a user logs
// so users see what they can do on a website
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <HeroSection />
        <Step />
        <Statistic />
        <Teams />
        <Footer />
        {children}
      </body>
    </html>
  )
}
