import { LazyContextProvider } from '@/context/useContextProvider'
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <LazyContextProvider>
          {children}
        </LazyContextProvider>
      </body>
      
    </html>
  )
}
