const tokenToUserData = require("../../utils/jwtToData")

test("equals some object", () => {
    expect(
        tokenToUserData("eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDhhMDY3MTMzNmNiNmRmNjM0ZjVlNTciLCJ1c2VybmFtZSI6IkFsaSBTaW5hIiwiZnVsbE5hbWUiOiJ0ZXN0IiwiZW1haWwiOiJ0ZXN0QGdtYWlsLmNvbSIsInByb2ZpbGVVcmwiOiJodHRwczovL2Nkbi1pY29ucy1wbmcuZmxhdGljb24uY29tLzUxMi80MjAyLzQyMDI4MzEucG5nIiwiYmlvIjoiUGFzc2lvbmF0ZSBzb2Z0d2FyZSBlbmdpbmVlciB3aXRoIGEgZmxhaXIgZm9yIHByb2JsZW0tc29sdmluZyBhbmQgYSBkZWRpY2F0aW9uIHRvIGNyYWZ0aW5nIGVmZmljaWVudCBhbmQgc2NhbGFibGUgc29sdXRpb25zLiBFeHBlcmllbmNlZCBpbiBmdWxsLXN0YWNrIGRldmVsb3BtZW50LCBJIHRocml2ZSBvbiB0cmFuc2Zvcm1pbmcgaW5ub3ZhdGl2ZSBpZGVhcyBpbnRvIHJvYnVzdCwgdXNlci1jZW50cmljIGFwcGxpY2F0aW9ucy4iLCJlZHVjYXRpb24iOiJHcmFkdWF0ZSIsIndvcmsiOiJwcm9ncmFtbWluZyIsInNvY2lhbHMiOltdLCJwZXJzb25hbFdlYnNpdGUiOm51bGwsImpvaW5lZCI6IjIwMjMtMDYtMTRUMTg6MjY6NTcuNTk4WiIsIl9fdiI6MCwiaWF0IjoxNzAwMzk2NDY1LCJleHAiOjE3MDA1NjkyNjV9.IdhEVSrR9sn2WwwtnUUcrIoqOobQG2NE1j3DI7rOCGI")
    ).toBe(true)
})